
server:
  port: ${APP_PORT:8070}
  servlet:
    context-path: /ms-membership
    
app:
  keystore:
    file: "C:/Users/moi/Desktop/Architecture_orientee_service/OUHIB_TP_SOA/ms-membership/src/main/resources/secrets/server.p12"
    alias: "esipe"
    password: "esipe"
   
management:
  security:
    enabled: false
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      #base-path: "/"
      exposure:
        include: info, health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
      atlas:
        enabled: false

security:
  require-ssl: false
  basic:
    enable: false
    
    